### ISSUE TITLE
Error while installing requirements.txt

### ISSUE THREAD

**Issue by seungjuchae** [DOsinga/deep_learning_cookbook#27]
OS : Window 10
Pip : 18.1
Python : 3.6

I have set a virtual environment using virtualenv following the manuels on the book
and tried to install ```requirements.txt``` using ```pip install -r requirements.txt```

However, it gives me following errors while installing the packages. 
Could you give me some advices what to do?
I have tried ```pip install --upgrade setuptools``` to check if it was out of date but it`s up to date and everything looks fine... except those errors

## Error with pyproj
```
Collecting pyproj==1.9.5.1 (from -r requirements.txt (line 82))
  Using cached https://files.pythonhosted.org/packages/29/72/5c1888c4948a0c7b736d10e0f0f69966e7c0874a660222ed0a2c2c6daa9f/pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "c:\users\seungj~1\desktop\progra~1\til\deeple~1\src\deeple~1\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-ppenl6wd\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\users\seung ju\appdata\local\programs\python\python36\Lib\distutils\_msvccompiler.py", line 345, in compile
        self.initialize()
      File "c:\users\seung ju\appdata\local\programs\python\python36\Lib\distutils\_msvccompiler.py", line 238, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\seungj~1\desktop\progra~1\til\deeple~1\src\deeple~1\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\seungj~1\desktop\progra~1\til\deeple~1\src\deeple~1\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\users\seungj~1\desktop\progra~1\til\deeple~1\src\deeple~1\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\users\seungj~1\desktop\progra~1\til\deeple~1\src\deeple~1\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-ppenl6wd\pyproj\
```

## Error with shapely
```
Collecting shapely==1.6.4.post1 (from -r requirements.txt (line 97))
  Downloading https://files.pythonhosted.org/packages/7d/3c/0f09841db07aabf9cc387662be646f181d07ed196e6f60ce8be5f4a8f0bd/Shapely-1.6.4.post1.tar.gz (224kB)
    100% |████████████████████████████████| 225kB 322kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-oi7jf2j7\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-oi7jf2j7\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\users\seung ju\appdata\local\programs\python\python36\Lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] \uc9c0\uc815\ub41c \ubaa8\ub4c8\uc744 \ucc3e\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-oi7jf2j7\shapely\
```

## Error with tensorflow 1.4.1
```
Collecting tensorflow==1.4.1 (from -r requirements.txt (line 104))
  Could not find a version that satisfies the requirement tensorflow==1.4.1 (from -r requirements.txt (line 104)) (from versions: 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0)
No matching distribution found for tensorflow==1.4.1 (from -r requirements.txt (line 104))

```

**Comment by DOsinga** [comment]
That is weird. The line:

`distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/`

Seems like looking into. Do you have that installed?

**Comment by seungjuchae** [comment]
@DOsinga 
Thanks, I have downloaded the "Microsoft Visual C++ Build Tools" and now I have no problem with pyproj module but still a problem remains  with shapely but this time, An OS error has emerged while installing the ```requirements.txt`` using pip. 

Any suggestion? Thank you very much in advance.

### Error with shapely
```
d/Shapely-1.6.4.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-vnwbc04r\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-vnwbc04r\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\users\seung ju\appdata\local\programs\python\python36\Lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] \uc9c0\uc815\ub41c \ubaa8\ub4c8\uc744 \ucc3e\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-vnwbc04r\shapely\
```

**Comment by DOsinga** [comment]
That error looks like something Korean maybe? Or at least the `\uc9c0\uc815\ub41c \ubaa8\ub4c8\uc744 \ucc3e\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4` bit.

It looks like getting shapely to work on Windows is tricky:

https://stackoverflow.com/questions/13144158/python-geos-and-shapely-on-windows-64

Has some suggestions. Starting from anaconda might be a good idea really. It gets you a lot of the other modules I am using. I've never used that on Windows though.

**Comment by DOsinga** [comment]
Any luck with this?

**Comment by seungjuchae** [comment]
@DOsinga No :( It just repeatedly giving me the same error.

![image](https://user-images.githubusercontent.com/33881908/50545693-c3c9aa80-0c19-11e9-8a5e-1db34f6928ef.png)

Following your suggestion, I tried with anaconda,  made a virtual environment using anaconda and tried to install the requirements.txt file using pip on the anaconda prompt.

However, the Error stays the same.


### Error with Shapely
```
Collecting shapely==1.6.4.post1 (from -r requirements.txt (line 97))
  Using cached https://files.pythonhosted.org/packages/7d/3c/0f09841db07aabf9cc387662be646f181d07ed196e6f60ce8be5f4a8f0bd/Shapely-1.6.4.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-tmhad1rz\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-tmhad1rz\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Users\Seung Ju\Anaconda3\envs\DeepLearningCB\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    **OSError: [WinError 126] \uc9c0\uc815\ub41c \ubaa8\ub4c8\uc744 \ucc3e\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4**
```


I also do not understand what that
```
 OSError: [WinError 126] \uc9c0\uc815\ub41c \ubaa8\ub4c8\uc744 \ucc3e\uc744 \uc218 
```
means so i simply comment it out by adding # in the requirements.txt ```#shapely==1.6.4.post1 ```

but then anther problem pops up with  ```geopandas``` 
for commenting shapely out.

### Error with shapely from geopandas
```
Collecting widgetsnbextension==3.1.0 (from -r requirements.txt (line 114))
  Using cached https://files.pythonhosted.org/packages/20/9c/bb3d5bad8be29ce1fe3f09b991c3ad8e05b0f97302b91c9fb13bdea94219/widgetsnbextension-3.1.0-py2.py3-none-any.whl
Collecting shapely (from geopandas==0.3.0->-r requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-qflihv3t\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-qflihv3t\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Users\Seung Ju\Anaconda3\envs\DeepLearningCB\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] \uc9c0\uc815\ub41c \ubaa8\ub4c8\uc744 \ucc3e\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SEUNGJ~1\AppData\Local\Temp\pip-install-qflihv3t\shapely\
```


Should i just comment geopanas out too? 



And It seems like pip can not find the tensorflow version 1.4.1 so i changed it to 1.4.0 which seem to work

**Comment by DOsinga** [comment]
What you could try is start with a anaconda environment and either install things on demand (anaconda should have most dependencies) without a version number, or after installing anaconda, try to install pip-tools:

    pip install pip-tools

and then do a fresh `pip-compile` to create a new `requirements.txt` - that might take care of the version mismatch you seem to have. I.e.:

    pip-compile
    pip install -r requirements.txt

Let me know if this works.

**Comment by seungjuchae** [comment]
@DOsinga 

Hi, first of all, Happy new year! 
I have installed all the dependencies by myself on Anaconda environment.

I have had problems with installing ``` pip install fiona``` and ``` pip install geopandas```  which seems like a solid and recurrent problem on window [fiona](https://github.com/Toblerity/Fiona/issues/449), [geopandas](https://stackoverflow.com/questions/34427788/how-to-successfully-install-pyproj-and-geopandas)

However
With the help of the [blog](https://geoffboeing.com/2014/09/using-geopandas-windows/),
i typed ```conda install -c conda-forge geopandas``` which installed a lot of packages including ```pyproj```, ```shapely```, ```geopandas```, ```fiona``` etc.. 
The rest of packages that were not installed using the above command, i installed each of them manually.

Thanks for helping me out!

**Comment by DOsinga** [comment]
It's good to hear it seems to work now. This really should be easier!
